# Generated by Django 4.2.11 on 2024-04-14 22:41

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_about_title_alter_faq_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Контент'),
        ),
    ]
